=== paadam94/webtech/01-hamlet/solution/play.dtd
<!ELEMENT play (author, title, act*)>
<!ELEMENT act (title, scene*)>
<!ELEMENT scene (title, paragraph*)>
<!ELEMENT paragraph (speaker?, (line | stagedir)*)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT speaker (#PCDATA)>
<!ELEMENT line (#PCDATA)>
<!ELEMENT stagedir (#PCDATA)>

=== paadam94/webtech/01-hamlet/solution/hamlet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE play SYSTEM "play.dtd">
<?xml-stylesheet type="text/css" href="play.css"?>

<!-- William Shakespeare -->
<!-- The Tragedy of Hamlet, Prince of Denmark -->
<!-- ACT I -->

<!-- SCENE V. Another part of the platform. -->

<!-- HAMLET -->
<!--     O all you host of heaven! O earth! What else? -->
<!--     And shall I couple hell? O, fie! Hold, hold, my heart; -->
<!--     And you, my sinews, grow not instant old, -->
<!--     But bear me stiffly up. Remember thee! -->
<!--     Ay, thou poor ghost, while memory holds a seat -->
<!--     In this distracted globe. Remember thee! -->
<!--     Yea, from the table of my memory -->
<!--     I'll wipe away all trivial fond records, -->
<!--     All saws of books, all forms, all pressures past, -->
<!--     That youth and observation copied there; -->
<!--     And thy commandment all alone shall live -->
<!--     Within the book and volume of my brain, -->
<!--     Unmix'd with baser matter: yes, by heaven! -->
<!--     O most pernicious woman! -->
<!--     O villain, villain, smiling, damned villain! -->
<!--     My tables,-\-meet it is I set it down, -->
<!--     That one may smile, and smile, and be a villain; -->
<!--     At least I'm sure it may be so in Denmark: -->
<!--     [Writing] -->
<!--     So, uncle, there you are. Now to my word; -->
<!--     It is 'Adieu, adieu! remember me.' -->
<!--     I have sworn 't. -->
<!-- [Enter HORATIO and MARCELLUS] -->
<!-- HORATIO -->
<!--     [Within] My lord, my lord,-\- -->
<!-- MARCELLUS -->
<!--     [Within] Lord Hamlet,-\- -->
<!-- HORATIO -->
<!--     [Within] Heaven secure him! -->
<!-- HAMLET -->
<!--     So be it! -->
<!-- HORATIO -->
<!--     [Within] Hillo, ho, ho, my lord! -->
<!-- HAMLET -->
<!--     Hillo, ho, ho, boy! come, bird, come. -->

<play>
  <author>William Shakespeare</author>
  <title>The Tragedy of Hamlet, Prince of Denmark</title>
  <act>
    <title>ACT I</title>
    <scene>
      <title>SCENE V. Another part of the platform.</title>
      <paragraph>
	<speaker>HAMLET</speaker>
	<line>O all you host of heaven! O earth! What else?</line>
	<line>And shall I couple hell? O, fie! Hold, hold, my heart;</line>
	<line>And you, my sinews, grow not instant old,</line>
	<line>But bear me stiffly up. Remember thee!</line>
	<line>Ay, thou poor ghost, while memory holds a seat</line>
	<line>In this distracted globe. Remember thee!</line>
	<line>Yea, from the table of my memory</line>
	<line>I'll wipe away all trivial fond records,</line>
	<line>All saws of books, all forms, all pressures past,</line>
	<line>That youth and observation copied there;</line>
	<line>And thy commandment all alone shall live</line>
	<line>Within the book and volume of my brain,</line>
	<line>Unmix'd with baser matter: yes, by heaven!</line>
	<line>O most pernicious woman!</line>
	<line>O villain, villain, smiling, damned villain!</line>
	<line>My tables,--meet it is I set it down,</line>
	<line>That one may smile, and smile, and be a villain;</line>
	<line>At least I'm sure it may be so in Denmark:</line>
	<line><stagedir>Writing</stagedir></line>
	<line>So, uncle, there you are. Now to my word;</line>
	<line>It is 'Adieu, adieu! remember me.'</line>
	<line>I have sworn 't.</line>
      </paragraph>
      <paragraph>
	<stagedir>Enter HORATIO and MARCELLUS</stagedir>
      </paragraph>
      <paragraph>
	<speaker>HORATIO</speaker>
	<line><stagedir>Within</stagedir> My lord, my lord,--</line>
      </paragraph>
      <paragraph>
	<speaker>MARCELLUS</speaker>
	<line><stagedir>Within</stagedir> Lord Hamlet,--</line>
      </paragraph>
      <paragraph>
	<speaker>HORATIO</speaker>
	<line><stagedir>Within</stagedir> Heaven secure him!</line>
      </paragraph>
      <paragraph>
	<speaker>HAMLET</speaker>
	<line>So be it!</line>
      </paragraph>
      <paragraph>
	<speaker>HORATIO</speaker>
	<line><stagedir>Within</stagedir> Hillo, ho, ho, my lord!</line>
      </paragraph>
      <paragraph>
	<speaker>HAMLET</speaker>
	<line>Hillo, ho, ho, boy! come, bird, come.</line>
      </paragraph>
    </scene>
  </act>
</play>
